# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import zorya.fields
import zorya.thumbs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstroCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('maxAscension', models.TimeField()),
                ('minAscension', models.TimeField()),
                ('maxDeclination', zorya.fields.DeclinationField(blank=True, null=True)),
                ('minDeclination', zorya.fields.DeclinationField(blank=True, null=True)),
                ('magnitudo', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='BibCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BugTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('dateandtime', models.DateTimeField(default=datetime.datetime.now)),
                ('userAgent', models.CharField(max_length=256)),
                ('author', models.EmailField(blank=True, max_length=254, null=True)),
                ('bugUrl', models.CharField(max_length=64)),
                ('addicionalinfo', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Constellations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('constellation', models.CharField(max_length=128, unique=True)),
                ('other_abbreviation', models.CharField(max_length=4, unique=True)),
                ('genitive', models.CharField(max_length=128, unique=True)),
                ('family', models.CharField(max_length=32)),
                ('origin', models.CharField(max_length=64)),
                ('meaning', models.CharField(max_length=128)),
                ('brightest_star', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactApplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', zorya.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'images')),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('photo_thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objects_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_number', models.IntegerField(blank=True, null=True)),
                ('object_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Catalogue', to='zorya.Catalogues')),
            ],
        ),
        migrations.CreateModel(
            name='ReletedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametype', models.CharField(max_length=80, unique=True)),
                ('shortcutnametype', models.CharField(max_length=32, unique=True)),
                ('phototype', zorya.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=b'images')),
                ('descriptiontype', models.TextField()),
                ('maintype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zorya.ReletedType', to_field=b'nametype')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='StellarObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otype', models.CharField(blank=True, max_length=24, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('type_shortcut', models.CharField(blank=True, max_length=12, null=True)),
                ('classe', models.CharField(blank=True, max_length=12, null=True)),
                ('rightAsc', models.TimeField(blank=True, null=True)),
                ('declination', zorya.fields.DeclinationField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('magnitudo', models.FloatField(blank=True, max_length=5, null=True)),
                ('dimAxb', models.CharField(blank=True, max_length=32, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('constelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatedconstellation', to='zorya.Constellations')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='StellarObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='zorya.StellarObject'),
        ),
        migrations.AddField(
            model_name='objects_list',
            name='single_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='zorya.StellarObject'),
        ),
        migrations.AddField(
            model_name='objectphotos',
            name='ngc_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='zorya.StellarObject'),
        ),
        migrations.AddField(
            model_name='bibcode',
            name='StellarObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibcode', to='zorya.StellarObject'),
        ),
    ]
