# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zorya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectphotos',
            name='photo_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='addicionalinfo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='stellarobject',
            name='constelation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedconstellation', to='zorya.Constellations'),
        ),
    ]
